# Generated by Django 5.1.7 on 2025-03-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectprofile',
            old_name='is_founding_member',
            new_name='is_staff',
        ),
    ]
