# Generated by Django 5.1.7 on 2025-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_is_founding_member_subjectprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectprofile',
            name='tarot_card_name',
            field=models.CharField(default='The Fool', max_length=255, unique=True),
        ),
    ]
