# Generated by Django 5.1.7 on 2025-03-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_profilefeeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='created_by',
        ),
    ]
